<?php

declare(strict_types=1);

namespace ADCT\ParishIntake\Core\Events;

use DateTimeImmutable;
use DateTimeZone;

/**
 * Turns two `adct_pi_event_changes` snapshots into the before/after summary an
 * approver reads before deciding whether to undo a change ([ADR 0008](0008-approval-by-dean-or-archdiocese-reviewer.md) point 4).
 *
 * The snapshots are written by `WordPressPublicationStore::snapshot()`,
 * `RevertChangeHandler::snapshot()` and `UnpublishEventHandler::snapshot()`, and
 * all three write the same shape:
 *
  *     ['title' => string, 'content' => string, 'excerpt' => string,
  *      'status' => string, 'event_type_term_ids' => int[], 'featured_image_id' => int,
 *      'meta' => ['parish_id' => mixed, 'venue_id' => mixed, 'start_local' => string,
 *                 'end_local' => string, 'all_day' => mixed, 'rrule' => string,
 *                 'exdates' => mixed, 'rdates' => mixed, 'featured' => mixed,
 *                 'status_flag' => string, 'source_candidate_id' => mixed,
 *                 'contact' => string]]
 *
 * Four properties matter and none of them are cosmetic:
 *
 * - **The unpublish row is a diff too.** `UnpublishEventHandler` writes a trail
 *   row holding the state that was live, exactly so that this class can say what
  *   an approver would lose by clicking the link. The `status` and
 *   `status_flag` rows carry that.
 * - **A missing side is not a change.** WordPress returns `''` for absent
 *   metadata, so an absent value and an empty string must read as the same
 *   "nothing", or every field gains a spurious "set" line the first time it is
 *   touched.
 * - **Nothing is echoed here.** Every value in these payloads came out of a
 *   parish bulletin and is hostile until escaped, so this returns plain text
 *   and the caller escapes each line. It never calls WordPress.
 * - **A value cannot forge a line.** `content` is free text from a parish
 *   and may contain newlines, so newlines are flattened before the value is
 *   shortened, not after.
 *
 * Day-first dates are the local convention: `12/10/2026` is 12 October (see
 * `docs/development.md`).
 */
final class ChangeDiff
{
    /**
     * Longest single value rendered in a summary line. A bulletin paragraph or
     * a pasted poster description can be thousands of characters; the approver
     * needs enough to recognise the change, not the whole document, and the
     * full text is one click away in the change history.
     */
    public const VALUE_LIMIT = 160;

    /**
     * The fields worth a line, in the order an approver reads them: what, then
     * whether it is on, then when, then where, then how it repeats.
     *
     * Each entry is label => path into the snapshot. A one-element path reads
     * the snapshot root; a two-element path reads into `meta`.
     *
     * `excerpt`, `exdates` and `rdates` never get a line. The excerpt is
     * generated by WordPress from the content, so a change to it is not
     * something an approver can act on separately, and the two recurrence
     * lists are internals whose effect already shows in the "Repeats" and
     * "Starts" lines. `contact` and `source_candidate_id` are excluded for a
     * different reason: a personal address and an internal id have no place in
     * a mail that goes to every approver holding the parish. All four stay in
     * the snapshot, because the revert handler restores the snapshot wholesale
     * and must not lose them.
     *
     * @var array<string, array{0: string, 1: list<string>}>
     */
    private const FIELDS = [
            'title' => ['Title', ['title']],
            'published_status' => ['Published status', ['status']],
        'status_flag' => ['Event status', ['meta', 'status_flag']],
        'start' => ['Starts', ['meta', 'start_local']],
        'end' => ['Ends', ['meta', 'end_local']],
        'all_day' => ['All day', ['meta', 'all_day']],
        'repeats' => ['Repeats', ['meta', 'rrule']],
        'parish' => ['Parish', ['meta', 'parish_id']],
        'venue' => ['Venue', ['meta', 'venue_id']],
            'content' => ['Description', ['content']],
        'featured' => ['Featured', ['meta', 'featured']],
        'featured_image' => ['Featured image', ['featured_image_id']],
        'event_type' => ['Event type', ['event_type_term_ids']],
    ];

    /**
     * Post status values WordPress uses for an event, with the wording the
     * events page uses. `adct_unpublished` is in here because the unpublish
     * trail row records it and "adct_unpublished" teaches an approver nothing.
     * The wording says what happened, not that it was approved.
     *
     * @var array<string, string>
     */
    private const POST_STATUSES = [
        'publish' => 'Published',
        'draft' => 'Draft',
        'pending' => 'Pending review',
        'private' => 'Private',
        'trash' => 'In the bin',
        'future' => 'Scheduled',
        'adct_unpublished' => 'Off the events page',
    ];

    /**
     * @var array<string, string>
     */
    private const STATUS_FLAGS = [
        'scheduled' => 'Going ahead',
        'cancelled' => 'Cancelled',
        'postponed' => 'Postponed',
    ];

    /**
     * One line per changed field, ready for the caller to escape.
     *
     * A field that did not change produces no line at all, so a change touching
     * only the time produces exactly one row rather than thirteen.
     *
     * @param array<string, mixed> $before
     * @param array<string, mixed> $after
     * @return list<array{label: string, before: string, after: string}>
     */
    public static function rows(array $before, array $after): array
    {
        $rows = [];

        foreach (self::FIELDS as [$label, $path]) {
            $from = self::read($before, $path);
            $to = self::read($after, $path);
            $fromText = self::render($label, $from);
            $toText = self::render($label, $to);
            // Compared as rendered, not as stored. Two snapshots can hold the
            // same fact in different shapes -- `null` and `''` are both "nothing"
            // because WordPress returns '' for metadata that was never written,
            // and a term list is a set, so [9,4] and [4,9] are the same event
            // type. A raw comparison would raise a line for a field nobody
            // touched, which is how an approver learns to skip the summary.
            if ($fromText === $toText) {
                continue;
            }
            $rows[] = ['label' => $label, 'before' => $fromText, 'after' => $toText];
        }

        return $rows;
    }

    /**
     * The same summary as prose, for a plain-text body or a log line.
     *
     * @param array<string, mixed> $before
     * @param array<string, mixed> $after
     */
    public static function describe(array $before, array $after): string
    {
        $lines = [];
        foreach (self::rows($before, $after) as $row) {
            $lines[] = $row['label'] . ': ' . $row['before'] . ' -> ' . $row['after'];
        }

        return implode("\n", $lines);
    }

    /**
     * Decode a stored `before_payload` / `after_payload` column.
     *
     * An unreadable payload is not a reason to abandon the batch: the caller is
     * told it was unreadable and still gets the change itself, because "the time
     * moved" beats no notice at all.
     *
     * @return array{ok: bool, snapshot: array<string, mixed>}
     */
    public static function decode(mixed $payload): array
    {
        if (is_array($payload)) {
            return ['ok' => true, 'snapshot' => $payload];
        }
        if (! is_string($payload) || trim($payload) === '') {
            return ['ok' => false, 'snapshot' => []];
        }
        $decoded = json_decode($payload, true);
        if (! is_array($decoded)) {
            return ['ok' => false, 'snapshot' => []];
        }

        return ['ok' => true, 'snapshot' => $decoded];
    }

    /**
     * @param array<string, mixed> $snapshot
     * @param list<string> $path
     */
    private static function read(array $snapshot, array $path): mixed
    {
        $value = $snapshot;
        foreach ($path as $segment) {
            if (! is_array($value) || ! array_key_exists($segment, $value)) {
                return null;
            }
            $value = $value[$segment];
        }

        return $value;
    }

    /**
     * Render one side of a diff. The label decides the wording, because the same
     * stored value reads differently depending on what it is: a `status` is
     * a WordPress status, a `status_flag` is one of three, and a `start_local`
     * is a local wall-clock time.
     */
    private static function render(string $label, mixed $value): string
    {
        if ($label === 'Published status') {
            return is_scalar($value) && (string) $value !== ''
                ? (self::POST_STATUSES[(string) $value] ?? self::shorten((string) $value))
                : '(none)';
        }
        if ($label === 'Event status') {
            return is_scalar($value) && (string) $value !== ''
                ? (self::STATUS_FLAGS[(string) $value] ?? self::shorten((string) $value))
                : '(none)';
        }
        if ($label === 'Starts' || $label === 'Ends') {
            return is_scalar($value) && (string) $value !== ''
                ? self::localDateTime((string) $value)
                : '(none)';
        }
                if ($label === 'All day' || $label === 'Featured') {
                    // WordPress stores these flags as the strings '0' and '1', so a
                    // raw render prints "Featured: 0 -> 1" and leaves the approver to
                    // work out which way round it went.
                    return is_scalar($value) && (string) $value !== ''
                        ? (self::isTruthy((string) $value) ? 'Yes' : 'No')
                        : '(none)';
                }
        if ($label === 'Repeats') {
            return is_scalar($value) && (string) $value !== ''
                ? RecurrenceSummary::describe((string) $value) . ' (' . (string) $value . ')'
                : 'Does not repeat';
        }

        return self::scalar($value);
    }

    /**
         * How WordPress writes a stored flag meta value: '1' and 'true' are set,
         * '0', 'false' and '' are not.
         */
        private static function isTruthy(string $value): bool
        {
            return in_array(strtolower(trim($value)), ['1', 'true', 'yes', 'on'], true);
        }

        /**
         * Anything that is not a string, a number or a list reads as "nothing"
     * rather than as the word "Array", so a malformed payload cannot put a PHP
     * notice into the body of a mail an approver is reading.
     */
    private static function scalar(mixed $value): string
    {
        if (is_bool($value)) {
            return $value ? 'Yes' : 'No';
        }
        if ($value === null || $value === '' || $value === []) {
            return '(none)';
        }
        if (is_array($value)) {
            $parts = [];
            foreach ($value as $item) {
                if (is_scalar($item) && (string) $item !== '') {
                    $parts[] = (string) $item;
                }
            }
            if ($parts === []) {
                return '(none)';
            }
            sort($parts, SORT_NATURAL | SORT_FLAG_CASE);

            return self::shorten(implode(', ', $parts));
        }
        if (! is_scalar($value)) {
            return '(none)';
        }

        return self::shorten(self::flatten((string) $value));
    }

    /**
     * Newlines become spaces and runs of whitespace collapse, so a multi-line
     * `content` cannot add a second apparent line to the plain-text body.
     */
    private static function flatten(string $value): string
    {
        $value = preg_replace('/\R/u', ' ', $value) ?? $value;
        $value = preg_replace('/[ \t]+/u', ' ', $value) ?? $value;

        return trim($value);
    }

    private static function shorten(string $value): string
    {
        if (mb_strlen($value) <= self::VALUE_LIMIT) {
            return $value;
        }

        return rtrim(mb_substr($value, 0, self::VALUE_LIMIT)) . '...';
    }

    /**
     * `Y-m-d\TH:i` in Africa/Johannesburg becomes `12/10/2026 18:30`, the
     * day-first form the rest of the plugin uses. A value that is not in that
     * shape is returned untouched rather than guessed at: an unreadable
     * timestamp is shown so a person can judge it, not silently reformatted
     * into a date that looks authoritative and is wrong.
     */
    private static function localDateTime(string $value): string
    {
        $date = DateTimeImmutable::createFromFormat(
            '!Y-m-d\TH:i',
            $value,
            new DateTimeZone('Africa/Johannesburg')
        );
        if ($date === false || $date->format('Y-m-d\TH:i') !== $value) {
            return $value;
        }

        return $date->format('d/m/Y H:i');
    }
}
