<?php

declare(strict_types=1);

namespace ADCT\ParishIntake\Tests\Unit\Core\Events;

use ADCT\ParishIntake\Core\Events\ChangeDiff;
use PHPUnit\Framework\TestCase;

final class ChangeDiffTest extends TestCase
{
    /**
     * A snapshot in exactly the shape WordPressPublicationStore::snapshot()
     * writes, so the fixture and the code cannot drift apart quietly.
     *
     * Overrides are merged, not unioned: `$a + $b` keeps the left operand's key,
     * so a union would silently ignore every override this fixture is given and
     * every test below would pass against the default snapshot.
     *
     * @param array<string, mixed> $meta
     * @param array<string, mixed> $root
     * @return array<string, mixed>
     */
    private static function snapshot(array $meta = [], array $root = []): array
    {
        $snapshot = [
                    'title' => 'Parish farewell Mass',
                    'content' => 'The usual end-of-term Mass.',
                    'excerpt' => '',
                    'status' => 'publish',
            'event_type_term_ids' => [4],
            'featured_image_id' => 0,
            'meta' => [
                'parish_id' => 12,
                'venue_id' => 3,
                'start_local' => '2026-10-12T09:00',
                'end_local' => '2026-10-12T10:00',
                'all_day' => '0',
                'rrule' => '',
                'exdates' => [],
                'rdates' => [],
                'featured' => '0',
                'status_flag' => 'scheduled',
                'source_candidate_id' => 88,
                'contact' => 'contact@example.test',
            ],
        ];

        return array_replace_recursive($snapshot, $root, ['meta' => $meta]);
    }

    public function testAnUnchangedSnapshotProducesNoRowsAtAll(): void
    {
        self::assertSame([], ChangeDiff::rows(self::snapshot(), self::snapshot()));
    }

    public function testOnlyTheFieldsThatChangedGetALine(): void
    {
        $after = self::snapshot(
            ['start_local' => '2026-10-12T18:30'],
            ['excerpt' => 'Regenerated by WordPress']
        );

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        self::assertCount(1, $rows);
        self::assertSame('Starts', $rows[0]['label']);
        self::assertSame('12/10/2026 09:00', $rows[0]['before']);
        self::assertSame('12/10/2026 18:30', $rows[0]['after']);
    }

    public function testADayFirstDateIsReadAsTwelveOctoberNotTheTwelfthMonth(): void
    {
        $after = self::snapshot(['start_local' => '2026-01-05T07:00']);
        $rows = ChangeDiff::rows(self::snapshot(), $after);

        // 2026-01-05 is 5 January. Rendering it as 05/01/2026 would be right,
        // but the ISO month/day order must never leak into the mail as
        // "2026-01-05", which an approver reads as a typo.
        self::assertSame('05/01/2026 07:00', $rows[0]['after']);
        self::assertStringNotContainsString('2026-01-05', ChangeDiff::describe(self::snapshot(), $after));
    }

    public function testEveryDocumentedFieldCanProduceARowOfItsOwn(): void
    {
        // Each entry is a path into the snapshot. A path naming a key no writer
        // ever produces is silently dead: the field simply never appears in a
        // summary, and the only symptom is a change notice with nothing in it.
        // Driving every path from a known snapshot is what makes that a failure
        // rather than an absence nobody notices.
        $changed = [
            'Title' => ['title' => 'Parish farewell Mass (moved)'],
            'Published status' => ['status' => 'draft'],
            'Event status' => ['meta' => ['status_flag' => 'postponed']],
            'Starts' => ['meta' => ['start_local' => '2026-10-12T18:30']],
            'Ends' => ['meta' => ['end_local' => '2026-10-12T11:00']],
            'All day' => ['meta' => ['all_day' => '1']],
            'Repeats' => ['meta' => ['rrule' => 'FREQ=WEEKLY;BYDAY=TU']],
            'Parish' => ['meta' => ['parish_id' => 13]],
            'Venue' => ['meta' => ['venue_id' => 5]],
            'Description' => ['content' => 'A different Mass.'],
            'Featured' => ['meta' => ['featured' => '1']],
            'Featured image' => ['featured_image_id' => 91],
            'Event type' => ['event_type_term_ids' => [4, 7]],
        ];

        foreach ($changed as $label => $override) {
            $rows = ChangeDiff::rows(self::snapshot(), self::snapshot([], $override));
            self::assertCount(1, $rows, $label . ' must be the only field that changed');
            self::assertSame($label, $rows[0]['label']);
            self::assertNotSame($rows[0]['before'], $rows[0]['after'], $label . ' must read as a change');
        }
    }

    public function testAnUnreadableTimestampIsShownAsWrittenRatherThanGuessedAt(): void
    {
        $after = self::snapshot(['start_local' => 'not-a-timestamp']);
        $rows = ChangeDiff::rows(self::snapshot(), $after);

        // Formatting it anyway would produce a date that looks authoritative
        // and is wrong, which is worse than admitting the value is broken.
        self::assertSame('not-a-timestamp', $rows[0]['after']);
    }

        public function testALooseTimestampIsNotQuietlyRewrittenIntoAValidOne(): void
        {
            // PHP's parser accepts a single-digit hour and normalises it, and it
            // silently ignores trailing data. Accepting either would hand an
            // approver a date the stored value never said, and would hide a payload
            // written by something that is not this plugin.
            foreach (['2026-10-12T9:00', '2026-10-12T09:00Z', '2026-10-12T09:00+02:00'] as $loose) {
                $rows = ChangeDiff::rows(self::snapshot(), self::snapshot(['start_local' => $loose]));
                self::assertSame($loose, $rows[0]['after'], $loose . ' must not be reformatted');
            }
        }

        public function testACanonicalTimestampIsStillFormatted(): void
        {
            $rows = ChangeDiff::rows(self::snapshot(), self::snapshot(['start_local' => '2026-11-04T07:15']));

            self::assertSame('Starts', $rows[0]['label']);
            self::assertSame('12/10/2026 09:00', $rows[0]['before']);
            self::assertSame('04/11/2026 07:15', $rows[0]['after']);
        }

    public function testCancellationIsShownInWordsRatherThanAsAStoredFlag(): void
    {
        $after = self::snapshot(
            ['status_flag' => 'cancelled'],
                        ['status' => 'publish']
        );

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        self::assertCount(1, $rows);
        self::assertSame('Event status', $rows[0]['label']);
        self::assertSame('Going ahead', $rows[0]['before']);
        self::assertSame('Cancelled', $rows[0]['after']);
    }

    public function testTheUnpublishTrailRowReadsAsAChangeOffTheEventsPage(): void
    {
        // UnpublishEventHandler appends a row holding the state that was live,
        // so an approver reading the notice learns what they would lose.
        $after = self::snapshot(
            ['status_flag' => ''],
                        ['status' => 'adct_unpublished']
        );

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        $labels = array_column($rows, 'label');
        self::assertContains('Published status', $labels);
        self::assertContains('Event status', $labels);
        self::assertStringNotContainsString('adct_unpublished', ChangeDiff::describe(self::snapshot(), $after));
    }

    public function testAnAbsentValueAndAnEmptyStringAreTheSameThing(): void
    {
        // WordPress returns '' for metadata that was never written. Treating
        // that as a change would give the approver a line for a field nobody
        // touched, on the very first change to the event.
        $before = self::snapshot();
        unset($before['meta']['venue_id']);
        $after = self::snapshot(['venue_id' => '']);

        self::assertSame([], ChangeDiff::rows($before, $after));
    }

    public function testASetFieldSaysSoRatherThanLeavingTheBeforeSideBlank(): void
    {
        $before = self::snapshot();
        unset($before['meta']['rrule']);
        $after = self::snapshot(['rrule' => 'FREQ=WEEKLY;BYDAY=SU']);

        $rows = ChangeDiff::rows($before, $after);

        self::assertCount(1, $rows);
        self::assertSame('Repeats', $rows[0]['label']);
        self::assertSame('Does not repeat', $rows[0]['before']);
        self::assertSame('Every Sunday (FREQ=WEEKLY;BYDAY=SU)', $rows[0]['after']);
    }

    public function testAClearedFieldIsShownAsNoneOnTheAfterSide(): void
    {
        $rows = ChangeDiff::rows(self::snapshot(), self::snapshot(['venue_id' => '']));

        self::assertSame('(none)', $rows[0]['after']);
        self::assertNotSame('(none)', $rows[0]['before']);
    }

    public function testTheParishContactAddressNeverReachesTheSummary(): void
    {
        // POPIA: a personal address has no place in a mail that goes to every
        // approver holding the parish, even though the snapshot keeps it so the
        // revert can restore it.
        $before = self::snapshot();
        $after = self::snapshot();
        $after['meta']['contact'] = 'someone.else@example.test';
        $after['meta']['source_candidate_id'] = 99;

        $described = ChangeDiff::describe($before, $after);

        self::assertSame('', $described);
        self::assertStringNotContainsString('someone.else@example.test', $described);
        self::assertStringNotContainsString('88', $described);
    }

    public function testTheExcludedGeneratedAndRecurrenceFieldsNeverGetALineOfTheirOwn(): void
    {
        $before = self::snapshot();
        $after = self::snapshot();
        $after['excerpt'] = 'Generated from the content';
        $after['meta']['exdates'] = ['2026-11-01T09:00'];
        $after['meta']['rdates'] = ['2026-12-24T18:00'];

        // These change on nearly every publication. A line for each would bury
        // the field an approver actually has to judge.
        self::assertSame([], ChangeDiff::rows($before, $after));
    }

    public function testAMultiLineDescriptionCannotForgeASecondSummaryLine(): void
    {
        $after = self::snapshot([], ['content' => "Line one.\nStarts: 01/01/2020 00:00 -> cancelled"]);

        $described = ChangeDiff::describe(self::snapshot(), $after);

        // The plain-text body is line-oriented, so a bulletin paragraph with a
        // newline in it must not read as a second changed field.
        self::assertSame(1, substr_count($described, "\n") + 1);
        self::assertStringContainsString('Line one. Starts: 01/01/2020 00:00 -> cancelled', $described);
    }

    public function testALongValueIsShortenedAndSaysThatItWas(): void
    {
        $long = str_repeat('a', ChangeDiff::VALUE_LIMIT + 200);
        $after = self::snapshot([], ['content' => $long]);

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        self::assertSame(ChangeDiff::VALUE_LIMIT + 3, mb_strlen($rows[0]['after']));
        self::assertStringEndsWith('...', $rows[0]['after']);
    }

    public function testAMultiByteValueIsCutOnACharacterBoundary(): void
    {
        $after = self::snapshot([], ['title' => str_repeat('é', ChangeDiff::VALUE_LIMIT + 50)]);

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        // Cutting bytes would leave half a character and a broken subject line
        // in every mail client.
        self::assertSame(1, preg_match('//u', $rows[0]['after']));
    }

    public function testTermIdsAreSortedSoAnUnchangedSetIsNotAChange(): void
    {
        $before = self::snapshot();
        $before['event_type_term_ids'] = [9, 4];
        $after = self::snapshot();
        $after['event_type_term_ids'] = [4, 9];

        self::assertSame([], ChangeDiff::rows($before, $after));
    }

    public function testATermListIsShownSortedAndAnEmptyOneAsNone(): void
    {
        $before = self::snapshot();
        $before['event_type_term_ids'] = [];
        $after = self::snapshot();
        $after['event_type_term_ids'] = [9, 4];

        $rows = ChangeDiff::rows($before, $after);

        self::assertSame('(none)', $rows[0]['before']);
        self::assertSame('4, 9', $rows[0]['after']);
    }

    public function testBooleansAndTruthyStoredFlagsBothReadAsYes(): void
    {
        // 'featured' is stored as the string '1' by WordPress, not as true, so
        // a strict boolean check would print 'No' for an event that is featured.
        $after = self::snapshot(['featured' => '1']);

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        self::assertSame('Featured', $rows[0]['label']);
        self::assertSame('No', $rows[0]['before']);
        self::assertSame('Yes', $rows[0]['after']);
    }

    public function testAListHeldInTheWrongTypeNeverLeaksTheWordArrayIntoAMail(): void
    {
            // get_the_terms() can hand back an object rather than a list if a
            // payload was written by hand. Whatever arrives, the mail must carry a
            // value or "(none)", never "Array", "Object" or a PHP warning.
            $before = self::snapshot();
            $before['event_type_term_ids'] = 'not-a-list';
            $after = self::snapshot();
            $after['event_type_term_ids'] = 4;

            $rows = ChangeDiff::rows($before, $after);

            self::assertSame('Event type', $rows[0]['label']);
            self::assertSame('not-a-list', $rows[0]['before']);
            self::assertSame('4', $rows[0]['after']);
            self::assertStringNotContainsString('Array', $rows[0]['after']);
        }

    public function testDecodeReadsAStoredColumnAndRefusesAnUnreadableOne(): void
    {
        $stored = json_encode(self::snapshot(), JSON_THROW_ON_ERROR);

        $read = ChangeDiff::decode($stored);
        self::assertTrue($read['ok']);
                self::assertSame('Parish farewell Mass', $read['snapshot']['title']);

        self::assertFalse(ChangeDiff::decode('{not json')['ok']);
        self::assertFalse(ChangeDiff::decode('')['ok']);
        self::assertFalse(ChangeDiff::decode(null)['ok']);
        self::assertFalse(ChangeDiff::decode('null')['ok']);
        // An unreadable payload must not look like a successful read of nothing,
        // or the caller would report a change with no fields as a real one.
        self::assertSame([], ChangeDiff::decode('{not json')['snapshot']);
    }

    public function testDecodeAcceptsAnAlreadyDecodedPayload(): void
    {
        $read = ChangeDiff::decode(self::snapshot());

        self::assertTrue($read['ok']);
                self::assertSame('Parish farewell Mass', $read['snapshot']['title']);
    }

    public function testARowIsNeverRenderedFromAValueThatIsNeitherScalarNorList(): void
    {
        $before = self::snapshot();
        $before['featured_image_id'] = new \stdClass();
        $after = self::snapshot();

        // get_post_thumbnail_id() returns an int, but a payload that has been
        // through json_decode cannot hold an object. Probing it anyway proves
        // the renderer has no branch that prints "Object" into a mail.
        $rows = ChangeDiff::rows($before, $after);

        self::assertCount(1, $rows);
        self::assertSame('(none)', $rows[0]['before']);
    }

    public function testAnUnknownStoredStatusIsShownAsStoredRatherThanDropped(): void
    {
        $after = self::snapshot();
        $after['status'] = 'a_status_added_by_another_plugin';

        $rows = ChangeDiff::rows(self::snapshot(), $after);

        self::assertSame('a_status_added_by_another_plugin', $rows[0]['after']);
    }
}
